import type { Metadata } from 'next';
import { CONTACT_EMAIL } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Terms of Service | MetaLens AI',
  description:
    'MetaLens AI terms of service — usage guidelines, disclaimers, limitation of liability, and acceptable use policy.',
  keywords:
    'MetaLens AI terms, terms of service, acceptable use, medical research tool terms, SPINAI',
};

export default function TermsPage() {
  return (
    <div className="max-w-[800px] mx-auto px-4 sm:px-6 py-16">
      <h1
        className="text-4xl font-bold text-[var(--color-text-primary)] mb-2"
        style={{ fontFamily: 'Outfit, sans-serif' }}
      >
        Terms of Service
      </h1>
      <p className="text-sm text-[var(--color-text-muted)] mb-8">Last Updated: April 6, 2026</p>

      <div className="bg-white rounded-2xl p-8 shadow-sm border border-[var(--color-border)] space-y-8">
        <p className="text-[var(--color-text-secondary)] leading-relaxed text-lg">
          Welcome to MetaLens AI. These Terms of Service (&quot;Terms&quot;) govern your access to
          and use of MetaLens AI (accessible at https://metalens-ai.com), operated by
          SPINAI (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing or using
          MetaLens AI, you agree to be bound by these Terms. If you do not agree to these Terms,
          you must not use the service.
        </p>

        <TermsSection title="1. Description of Service">
          <p>
            MetaLens AI is an AI-powered medical research tool that queries the PubMed biomedical
            database and uses Google Gemini AI to generate structured meta-analysis summaries. The
            service is provided as a research and educational tool and is intended to assist users
            in exploring the medical literature. MetaLens AI is available in both free and paid
            subscription tiers, with different levels of functionality and usage limits.
          </p>
        </TermsSection>

        <TermsSection title="2. Medical Disclaimer">
          <p>
            <strong>
              MetaLens AI is NOT a medical device, diagnostic tool, or clinical decision support
              system.
            </strong>{' '}
            The information provided by MetaLens AI is generated by artificial intelligence and is
            derived from published research literature available in the PubMed database. It is
            intended for informational and educational purposes only.
          </p>
          <p className="mt-2">
            The content generated by MetaLens AI does not constitute medical advice, diagnosis,
            or treatment recommendations. You should not rely on MetaLens AI outputs to make
            clinical decisions, diagnose medical conditions, or prescribe treatments. Always
            consult a qualified healthcare professional for medical advice. Never disregard
            professional medical advice or delay seeking treatment because of information obtained
            through MetaLens AI.
          </p>
          <p className="mt-2">
            AI-generated summaries may contain inaccuracies, misinterpretations, or incomplete
            information. Users are responsible for independently verifying all findings against
            the original source publications before relying on them for any purpose.
          </p>
        </TermsSection>

        <TermsSection title="3. Account Registration and Security">
          <p>
            To access certain features of MetaLens AI, you may be required to create an account
            through our authentication provider, Clerk. You agree to provide accurate and complete
            registration information, keep your account credentials confidential, and notify us
            immediately of any unauthorized use of your account. You are responsible for all
            activity that occurs under your account. We reserve the right to suspend or terminate
            accounts that violate these Terms.
          </p>
        </TermsSection>

        <TermsSection title="4. Acceptable Use Policy">
          <p>You agree to use MetaLens AI only for lawful purposes and in accordance with these Terms. You agree NOT to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Use MetaLens AI for any illegal, harmful, or fraudulent activity</li>
            <li>Attempt to gain unauthorized access to our systems, servers, or databases</li>
            <li>Use automated scripts, bots, or scrapers to access the service without our written permission</li>
            <li>Interfere with or disrupt the integrity or performance of MetaLens AI</li>
            <li>Reverse engineer, decompile, or disassemble any aspect of the service</li>
            <li>Resell, redistribute, or sublicense access to MetaLens AI without authorization</li>
            <li>Use the service to generate content that is misleading, defamatory, or harmful</li>
            <li>Violate the intellectual property rights of any third party</li>
            <li>Circumvent usage limits, rate limits, or subscription restrictions</li>
            <li>Use MetaLens AI outputs as a substitute for professional medical judgment in clinical settings</li>
          </ul>
        </TermsSection>

        <TermsSection title="5. Subscription Plans and Payments">
          <p>
            MetaLens AI offers Free and Pro subscription tiers. The Free tier provides
            limited functionality at no cost. The Pro tier requires a recurring
            subscription payment and offers expanded features, including increased numbers of
            abstracts analyzed per query and higher monthly usage limits. Subscription fees are
            billed in advance on a monthly or annual basis, depending on your chosen plan. All
            fees are non-refundable except as required by applicable law or as stated in our
            refund policy. We reserve the right to modify subscription pricing with 30 days&apos;
            prior notice.
          </p>
        </TermsSection>

        <TermsSection title="6. Intellectual Property">
          <p>
            The MetaLens AI service, including its design, code, user interface, logos, and
            branding, is the intellectual property of SPINAI and is protected by applicable
            copyright, trademark, and other intellectual property laws. You are granted a limited,
            non-exclusive, non-transferable license to use MetaLens AI for personal, educational,
            and professional research purposes in accordance with these Terms.
          </p>
          <p className="mt-2">
            The meta-analysis summaries generated by MetaLens AI are AI-generated outputs derived
            from publicly available PubMed abstracts. You may use these outputs for personal,
            educational, and research purposes. However, the underlying research papers cited in
            the summaries are the intellectual property of their respective authors and publishers,
            and are subject to their own copyright terms.
          </p>
        </TermsSection>

        <TermsSection title="7. Third-Party Services and Content">
          <p>
            MetaLens AI relies on third-party services including PubMed (National Library of
            Medicine), Google Gemini AI, Clerk (authentication), Google Analytics,
            and Vercel (hosting). We are not responsible for the availability, accuracy, or
            policies of these third-party services. Your use of MetaLens AI may be subject to the
            terms and policies of these third-party providers. We do not endorse, warrant, or
            guarantee any third-party content or service.
          </p>
        </TermsSection>

        <TermsSection title="8. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SPINAI AND ITS OFFICERS,
            DIRECTORS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO
            LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Your access to or use of (or inability to access or use) MetaLens AI</li>
            <li>Any conduct or content of any third party on the service</li>
            <li>Any content obtained from the service, including AI-generated summaries</li>
            <li>Unauthorized access, use, or alteration of your transmissions or content</li>
            <li>Any medical decisions made based on information provided by MetaLens AI</li>
          </ul>
          <p className="mt-2">
            IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE AMOUNT YOU
            HAVE PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED U.S.
            DOLLARS ($100), WHICHEVER IS GREATER.
          </p>
        </TermsSection>

        <TermsSection title="9. Disclaimer of Warranties">
          <p>
            METALENS AI IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS
            WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
            TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
            NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE,
            OR ERROR-FREE, OR THAT THE AI-GENERATED CONTENT WILL BE ACCURATE, COMPLETE, OR
            RELIABLE. WE DO NOT WARRANT THAT THE RESULTS OBTAINED FROM THE USE OF THE SERVICE
            WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS.
          </p>
        </TermsSection>

        <TermsSection title="10. Indemnification">
          <p>
            You agree to indemnify, defend, and hold harmless SPINAI and its officers, directors,
            employees, and agents from and against any claims, liabilities, damages, losses, and
            expenses (including reasonable attorneys&apos; fees) arising out of or in any way
            connected with: (a) your access to or use of MetaLens AI; (b) your violation of these
            Terms; (c) your violation of any third-party rights; or (d) any medical or clinical
            decisions made based on information obtained through MetaLens AI.
          </p>
        </TermsSection>

        <TermsSection title="11. Termination">
          <p>
            We reserve the right to suspend or terminate your access to MetaLens AI at any time,
            with or without cause, and with or without notice. Upon termination, your right to use
            the service will immediately cease. Provisions of these Terms that by their nature
            should survive termination shall survive, including but not limited to ownership
            provisions, warranty disclaimers, indemnification, and limitations of liability.
          </p>
        </TermsSection>

        <TermsSection title="12. Modifications to the Service and Terms">
          <p>
            We reserve the right to modify, suspend, or discontinue MetaLens AI (or any part
            thereof) at any time, with or without notice. We also reserve the right to modify
            these Terms at any time. When we make material changes, we will update the &quot;Last
            Updated&quot; date at the top of this page. Your continued use of MetaLens AI after
            any changes constitutes your acceptance of the revised Terms.
          </p>
        </TermsSection>

        <TermsSection title="13. Governing Law and Dispute Resolution">
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            Republic of Korea, without regard to its conflict of law provisions. Any disputes
            arising from or relating to these Terms or your use of MetaLens AI shall be resolved
            through good-faith negotiation. If negotiation fails, disputes shall be submitted to
            the exclusive jurisdiction of the courts located in Seoul, Republic of Korea.
          </p>
        </TermsSection>

        <TermsSection title="14. Severability">
          <p>
            If any provision of these Terms is found to be unenforceable or invalid by a court of
            competent jurisdiction, that provision shall be limited or eliminated to the minimum
            extent necessary, and the remaining provisions of these Terms shall remain in full
            force and effect.
          </p>
        </TermsSection>

        <div className="pt-4 border-t border-[var(--color-border)]">
          <p className="text-[var(--color-text-secondary)]">
            If you have any questions about these Terms of Service, please contact us at{' '}
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="text-[var(--color-primary)] hover:underline"
            >
              {CONTACT_EMAIL}
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}

function TermsSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2
        className="text-lg font-semibold text-[var(--color-text-primary)] mb-2"
        style={{ fontFamily: 'Outfit, sans-serif' }}
      >
        {title}
      </h2>
      <div className="text-[var(--color-text-secondary)] leading-relaxed">
        {children}
      </div>
    </div>
  );
}
